### ISSUE TITLE
Error while encoding

### ISSUE THREAD

**Issue by abinashsinha330** [JohnGiorgi/DeCLUTR#260] opened 2022-10-13 03:17 UTC
I am running the sample code snippet as shared on your repo as shown below:

```
from declutr import Encoder

# This can be a path on disk to a model you have trained yourself OR
# the name of one of our pretrained models.
pretrained_model_or_path = "declutr-small"

encoder = Encoder(pretrained_model_or_path)
embeddings = encoder([
    "A smiling costumed woman is holding an umbrella.",
    "A happy woman in a fairy costume holds an umbrella."
])
```

I get the below error:

```
File "/Users/some_user/Documents/sample/DeCLUTR/declutr/encoder.py", line 60, in __init__
    common_util.import_module_and_submodules("declutr")
  File "/opt/miniconda3/envs/og_py/lib/python3.8/site-packages/allennlp/common/util.py", line 376, in import_module_and_submodules
    import_module_and_submodules(subpackage, exclude=exclude)
  File "/opt/miniconda3/envs/og_py/lib/python3.8/site-packages/allennlp/common/util.py", line 359, in import_module_and_submodules
    module = importlib.import_module(package_name)
  File "/opt/miniconda3/envs/og_py/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/some_user/Documents/sample/DeCLUTR/declutr/dataset_reader.py", line 21, in <module>
    class DeCLUTRDatasetReader(DatasetReader):
  File "/Users/some_user/Documents/sample/DeCLUTR/declutr/dataset_reader.py", line 145, in DeCLUTRDatasetReader
    def text_to_instance(self, text: str) -> Instance:  # type: ignore
  File "/opt/miniconda3/envs/og_py/lib/python3.8/site-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/opt/miniconda3/envs/og_py/lib/python3.8/site-packages/overrides/overrides.py", line 117, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/opt/miniconda3/envs/og_py/lib/python3.8/site-packages/overrides/overrides.py", line 138, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/opt/miniconda3/envs/og_py/lib/python3.8/site-packages/overrides/signature.py", line 106, in ensure_signature_is_compatible
    ensure_all_positional_args_defined_in_sub(
  File "/opt/miniconda3/envs/og_py/lib/python3.8/site-packages/overrides/signature.py", line 220, in ensure_all_positional_args_defined_in_sub
    raise TypeError(f"{method_name}: `{super_param.name}` must be present")
TypeError: DeCLUTRDatasetReader.text_to_instance: `inputs` must be present
```

Please help me resolve this.

**Comment by JohnGiorgi** [comment] 2022-10-13 14:35
Thanks for raising an issue, I will try to look into this. Looks like the issue is on the AllenNLP side of things. Unless you really need to use AllenNLP, can you try using it from HuggingFace Transformers instead? Instructions [here](https://huggingface.co/johngiorgi/declutr-base)

**Comment by abinashsinha330** [comment] 2022-10-21 19:55
I am planning to do pre-training on the unlabeled dataset that I have with me. This error is stopping me to do so.

**Comment by JohnGiorgi** [comment] 2022-10-21 20:04
Can you provide more information on your environment, please? E.g. OS, python version, AllenNLP version, the commands you used to install DeCLUTR, etc... 

Looking at the error, my best guess is that you have installed a newer version of AllenNLP than is supported by this repo. In [the version of AllenNLP required by this repo](https://github.com/JohnGiorgi/DeCLUTR/blob/3eee0e185ac57572231785ec8113248fb7668e52/setup.py#L44), the `text_to_instance` method of `DatasetReader` (which is inherited by our [`DeCLUTRDatasetReader`](https://github.com/JohnGiorgi/DeCLUTR/blob/3eee0e185ac57572231785ec8113248fb7668e52/declutr/dataset_reader.py#L21)) accepts an argument `text`. However, in newer versions of AllenNLP this argument is called `inputs`. Hence the error: `TypeError: DeCLUTRDatasetReader.text_to_instance: `inputs` must be present`.

You can check the version of AllenNLP you have installed by running

```
pip freeze | grep "allennlp*"
```

in your python environment where you have installed this repo.

**Comment by JohnGiorgi** [comment] 2023-02-06 23:14
Closing, please re-open if I didn't solve your issue!

**Closed by JohnGiorgi** 2023-02-06 23:14 UTC
