### ISSUE TITLE
Training notebook not working

### ISSUE THREAD

**Issue by kingafy** [JohnGiorgi/DeCLUTR#203] opened 2021-04-14 06:29 UTC
```bash
!allennlp train "declutr_small.jsonnet" \
    --serialization-dir "output" \
    --overrides "$overrides" \
    --include-package "declutr" \
    -f
```

In this section I am getting error :
```
  File "/usr/local/lib/python3.7/dist-packages/declutr/common/contrastive_utils.py", line 50, in sample_anchor_positive_pairs
    f"len({tok_method}) should be at least {num_anchors * max_span_len * 2}"
ValueError: len(text.split()) should be at least 2048 (num_anchors * max_span_len * 2), got 614.
```

I have set min_length = 200. Kindly advise.

**Comment by JohnGiorgi** [comment] 2021-04-14 15:30
Please check the length of the smallest document in your corpus. The problem is that there is at least one document (with a length of 614) that is less than the required minimum length (`num_anchors * max_span_len * 2 or 2048`). This is mentioned [here](https://github.com/JohnGiorgi/DeCLUTR#gotchas-1) and [here](https://colab.research.google.com/github/JohnGiorgi/DeCLUTR/blob/master/notebooks/training.ipynb#scrollTo=uwnLpUmN4Art).

There are three solutions,

1. Lower `max_span_length` so that num_anchors * max_span_len * 2 <= the length of the shorted document in your corpus
2. Remove any documents with a length less than num_anchors * max_span_len * 2 from your dataset
3. Reduce `num_anchors`

Some combination of 1 and 2 would be the best. Reducing `num_anchors` will likely hurt performance.

**Comment by kingafy** [comment] 2021-04-15 04:13
I have created my own input file which is not wiki one. How to preprocess it to remove the ones not satisfying the criteria?

**Comment by kingafy** [comment] 2021-04-15 04:34
Where can i put the overides for max_span_len in the training notebook..Can it be done in the below section:-
overrides = (
    f"{{'train_data_path': '{train_data_path}', "
    # lower the batch size to be able to train on Colab GPUs
    f"'data_loader.batch_size': 2, "
    # training examples / batch size. Not required, but gives us a more informative progress bar during training
    f"'data_loader.batches_per_epoch': 8912}}"
)

**Comment by JohnGiorgi** [comment] 2021-04-15 13:59
> I have created my own input file which is not wiki one. How to preprocess it to remove the ones not satisfying the criteria?

This is mainly up to you. If your corpus of documents was stored as a list of strings (e.g. `documents`) then in python you could do something like:

```python
min_len = # ... some int
filtered_documents = [doc for doc in documents if len(doc.split()) > min_len]
```

You can see how we do it in the `preprocess_wikitext_103.py` script [here](https://github.com/JohnGiorgi/DeCLUTR/blob/349a58bcc829deba45860f617b3e2052287857ca/scripts/preprocess_wikitext_103.py#L101-L106)

**Comment by JohnGiorgi** [comment] 2021-04-15 14:01
> Where can i put the overides for `max_span_len` in the training notebook..Can it be done in the below section:-
> 
> ```
> overrides = (
>     f"{{'train_data_path': '{train_data_path}', "
>     # lower the batch size to be able to train on Colab GPUs
>     f"'data_loader.batch_size': 2, "
>     # training examples / batch size. Not required, but gives us a more informative progress bar during training
>     f"'data_loader.batches_per_epoch': 8912}}"
> )
> ```

Yes exactly, it is a parameter of `data_loader`, so you add it by specifying `'data_loader.max_span_len': some_int_here`. Let me know if that works!

**Comment by kingafy** [comment] 2021-04-16 04:13
When I am adding the extra parameter it is giving me error :-- 
 "Extra parameters passed to {}: {}".format(class_name, self.params)
allennlp.common.checks.ConfigurationError: Extra parameters passed to PyTorchDataLoader: {'max_span_len': 20}

So far I have not been able to process my native text file .NEither I am able to preprocess it nor train it due to the length constraint.

**Comment by JohnGiorgi** [comment] 2021-04-19 19:58
@kingafy Will you please copy the entire `allennlp train` command, with all arguments and overrides? It is hard to debug the issue without that

**Comment by JohnGiorgi** [comment] 2021-05-06 13:30
Closing, but please let me know if the issue is not addressed and don't hesitate to open another issue.

**Closed by JohnGiorgi** 2021-05-06 13:30 UTC
